### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by ahnyeji** [hd132506/OSS-3rd-project#4]
Make a list for promotion.
The site (where to promote) and the way to promote our project.

**Comment by ahnyeji** [comment]
Please make them md file!

**Comment by Songhaeissorry** [comment]
저는 이제까지 레딧에 가입했고, 여러 홍보 수단을 검색하여 윤영훈에게 전달함. 그로써 홍보역할은 윤영훈으로 교체.
